### ISSUE TITLE
RFE: Migrate datadog-service to cp-connector/go-sdk 

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#56]
**Problem statement.**
datadog-service uses the distributor sidecar for intercepting events from the shipyard-controller. Using distributor creates a problem where 
- [you can't use local development tools like Telepresence or you need to find a workaround](https://vadasambar.com/post/kubernetes/keptn/telepresence-issue/) 
- you need to run another sidecar with your service (for example, this makes it harder to look at logs from both the services at the same time)

**Describe the solution you'd like**
Whatever distributor is doing right now should go inside datadog-service i.e., we replace the sidecar with a library which does the same thing as the distributor. We can use the [`cp-connector` library or `go-sdk`](https://github.com/keptn/go-utils/) in place of distributor

**Describe alternatives you've considered**
I haven't considered any other alternatives which don't use a sidecar. 

**Additional context**

### TODO
- [ ] PoC and see if we can use cp-connector or go-sdk in place of distributor (tests should pass; check [this](https://github.com/keptn-sandbox/datadog-service/issues/53#issuecomment-1221904605) for how to run tests)
- [ ] Create an issue to try it out with local development tools like Telepresence (so that we can add docs around it in our README)
- [ ] If the PoC works fine, raise a PR to migrate datadog-service to go-sdk or cp-connector
