### ISSUE TITLE
Migrate `github.com/keptn/go-utils` to the same version as the datadog-service (or Keptn) version

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#64]
**Problem statement.**
[Right now we use an older version](https://github.com/keptn-sandbox/datadog-service/blob/719e528bf6811f1643ab7d4368630dfbe203a665/go.mod#L10) (0.15.0) of `github.com/keptn/go-utils` for datadog-service versions greater than 0.15.0. It'd be good to match the `github.com/keptn/go-utils` with the datadog-service version. go-utils matches Keptn versions i.e., if Keptn version is 0.15.0, go-utils version would (and should) be 0.15.0

**Describe the solution you'd like**
X version of datadog-service should use X version of go-utils. e.g.,
0.15.1 version of datadog-service should use [0.15.1 version of go-utils](https://github.com/keptn/go-utils/releases/tag/v0.15.1)
0.16.1 version of datadog-service should use [0.16.1 version of go-utils](https://github.com/keptn/go-utils/releases/tag/v0.16.1) 

**Describe alternatives you've considered**
I don't think there are any alternatives here. 

**TODO**
- [ ] Upgrade the version in `go.mod` for datadog-service versions > 0.15.1
- [ ] Raise a PR against `release-0.15.1` (or any other datadog-service version you are working with)
- [ ] Run the e2e integration tests for your branch (go [here](https://github.com/keptn-sandbox/datadog-service/actions/workflows/integration-tests.yaml) and manually trigger integration tests for your branch as shown in the screenshot below)
![image](https://user-images.githubusercontent.com/34534103/187844610-f4b313a3-4589-4d62-8a25-d0ee332251f8.png)
