### ISSUE TITLE
Integration tests fail for keptn version < 0.18.x (expected) and create a Github issues 

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#71]
**Summary** 
Current code in `master` branch of the datadog-service is incompatible with Keptn versions < 0.18.x due to a breaking change in Keptn. We run the integration tests for 5 Keptn versions 
https://github.com/keptn-sandbox/datadog-service/blob/72017a4d76ca98fd9fe780d31053bf80c5627026/.github/workflows/integration-tests.yaml#L22
When the tests run, the workflow fails for 0.16.0 and 0.17.0 version of Keptn which is expected but it creates a Github issue of `type:critical` which can confuse people. 
We should remove the 0.16.0 and 0.17.0 version from the workflow above. 

**Affected Component**

* [ ] Web UI / Bridge
* [ ] CLI
* [ ] REST API or webhooks
* [ ] User experience
* [ ] Developer experience
* [ ] Deployment/management with Helm

**To Reproduce**
The integration tests workflow runs every day. You can check a new issue of `type:critical` is created everyday in https://github.com/keptn-sandbox/datadog-service/issues

**Expected behavior**
The workflow should not create a Github issue
**Current behavior**
The workflow creates a Github issue everyday. 

**Screenshots**

**Additional context**

**TODO**
- [ ] Remove 0.16.0 and 0.17.0 from the integration tests above
- [ ] Make sure the Integration tests pass by running it for your PR branch from [here](https://github.com/keptn-sandbox/datadog-service/actions/workflows/integration-tests.yaml)
![image](https://user-images.githubusercontent.com/34534103/191679462-c39fca6c-a444-48aa-bcba-7b42ef85c7ca.png)
- [ ] Paste a screenshot or a link in the PR
- [ ] Get the PR reviewed and merge
- DONE

**Comment by vadasambar** [comment]
Failure on 23rd Sep 2022: https://github.com/keptn-sandbox/datadog-service/issues/74

**Comment by TarangVerma** [comment]
can i work on this issue.

**Comment by vadasambar** [comment]
@TarangVerma yes and thank you for showing interest. I will assign the issue to you.

**Comment by vadasambar** [comment]
If you need help, you can reach out to me on keptn slack (username: @vadasambar

**Comment by TarangVerma** [comment]
sure, thankyou...
