### ISSUE TITLE
Fix datadog-service does not show up in under `Observability` or `SLI Providers` on Keptn integrations page

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#75]
**Problem statement.**
This is a problem with the post 0.15.0 version of datadog-service. Originally noticed by @StackScribe [on slack](https://keptn.slack.com/archives/CGS5TA283/p1663837560156409?thread_ts=1663828386.324379&cid=CGS5TA283).

datadog-service doesn't show up under `Observability` or `SLI Providers` section
![image](https://user-images.githubusercontent.com/34534103/191907254-c304e910-2024-481f-87da-f795de34c2c6.png)
![image](https://user-images.githubusercontent.com/34534103/191907362-ff88baa4-ef47-43d4-aaa3-3ef984890dc4.png)

This happens because the post 0.15.0 version of datadog-service do not have the right keywords
https://github.com/keptn-sandbox/artifacthub/blob/9cd650443500d0c3c9dfa81bf43ac5c34a798740/datadog-service/0.19.0/artifacthub-pkg.yml#L9-L11
As opposed to 0.15.0 version:
https://github.com/keptn-sandbox/artifacthub/blob/d4d94067d033ca1627ca4f7880eb1918cd13daee/datadog-service/0.15.0/artifacthub-pkg.yml#L9-L14

**Describe the solution you'd like**
We need to add the following keywords to `artifacthub-pkg.yml` of all datadog-service folders listed [here](https://github.com/keptn-contrib/artifacthub/tree/9cd650443500d0c3c9dfa81bf43ac5c34a798740/datadog-service) (if the keyword is already there skip it):
```
- keptn
- sandbox
- observability
- monitoring
- sli-provider
- datadog
- datadog-service
```

**TODO**
- [ ] Raise a PR with the above change
- [ ] Ask for review in #keptn-integrations channel (mention `@vadasambar` to let him know)
- [ ] Get the PR reviewed (note: you probably won't have the permission to merge the PR in https://github.com/keptn-contrib/artifacthub repo. Ask the reviewer to merge the PR)
- DONE

**Comment by TarangVerma** [comment]
can i work on this issue...

**Comment by vadasambar** [comment]
I have assigned you to the issue. Thank you!
