### ISSUE TITLE
Add logo and fix the display name of the datadog-service integration in ArtifactHub

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#76]
**Problem statement.**
Right now, if you search for `datadog-service` on ArtifactHub, you can see that datadog does not have a logo and the display name shows up as `datadog-service` instead of `Datadog Service`
![image](https://user-images.githubusercontent.com/34534103/191908435-6452494c-7ebb-474d-a8fb-9247c8397e26.png)
Here's how Prometheus Service looks like:
![image](https://user-images.githubusercontent.com/34534103/191908602-6bb9b1d2-9a97-4cf2-99b2-c24e30f96234.png)

**Describe the solution you'd like**
1. Fix the [`displayName` parameter](https://github.com/keptn-contrib/artifacthub/blob/9cd650443500d0c3c9dfa81bf43ac5c34a798740/datadog-service/0.19.0/artifacthub-pkg.yml#L3) for all versions of datadog-service in the keptn artifacthub repo [here](https://github.com/keptn-contrib/artifacthub/tree/9cd650443500d0c3c9dfa81bf43ac5c34a798740/datadog-service)
2. Use the following logo from https://www.datadoghq.com/about/resources/
![image](https://user-images.githubusercontent.com/34534103/191908897-039da45e-d4ea-44c6-b701-96ec61bdf934.png)
You will have to add a `logoUrl` parameter in the artifacthub-pkg.yml (for example check [this](https://github.com/keptn-contrib/artifacthub/blob/9cd650443500d0c3c9dfa81bf43ac5c34a798740/prometheus/0.9.1/artifacthub-pkg.yml#L6) in Prometheus Service). Datadog does not have a logo Url you can use like Prometheus Service. We will have to download the logo, add it under `images/` (<- create a new folder [here](https://github.com/keptn-contrib/artifacthub/tree/main/datadog-service)) and use the link like [this](https://github.com/keptn-contrib/artifacthub/blob/2fce275eb9ca9e13b64fafe9e0dba20e5bf4fe10/artillery/0.3.1/artifacthub-pkg.yml#L8)

**TODO**
- [ ] Raise a PR with the above change
- [ ] Ask for review in #keptn-integrations channel (mention `@vadasambar` so that he can help you out in case of problems)
- [ ] Get the PR reviewed (note: you probably won't have the permission to merge the PR in https://github.com/keptn-contrib/artifacthub repo. Ask the reviewer to merge the PR)
- DONE

**Comment by vadasambar** [comment]
Re-opened because the changes merged in the PR above have not been reflected yet
![image](https://user-images.githubusercontent.com/34534103/193741196-cee434f9-49db-45dd-ad53-2769149799a9.png)

**Comment by tarangverma** [comment]
can i take up this issue...

**Comment by vadasambar** [comment]
Assigned you @tarangverma .

**Comment by tarangverma** [comment]
https://github.com/keptn-contrib/artifacthub/pull/189

**Comment by tehami94** [comment]
Is this issue open? I would like to work on it if it is open. @vadasambar
