### ISSUE TITLE
Add some automation around checking commit style

### ISSUE THREAD

**Issue by vadasambar** [keptn-sandbox/datadog-service#94]
**Problem statement.**
Some of the contributors to datadog-service haven't contributed to Keptn before so they usually don't know the [commit](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#commit-types-and-scopes) and the [PR style](https://github.com/keptn/keptn/blob/master/CONTRIBUTING.md#make-a-pull-request) we follow. We have to tell them about this when they make their first PR. 

**Describe the solution you'd like**
It'd be nice to have an automated check for commit and PR style. It could be a github workflow on PRs. The check should also suggest the right way to do things (i.e., how to fix the current commit or PR)

**Additional context**
We have a [similar check in Keptn](https://github.com/keptn/keptn/actions/runs/3171957555/jobs/5165919432) for PR titles (we use [this](https://github.com/amannn/action-semantic-pull-request) github action for that)

**TODO**
- [ ] Add PR title check
- [ ] Add PR commit check
- [ ] Make sure they work (screenshots or something else which makes it easier to review)
- [ ] Raise a PR and get it reviewed
- DONE

**Comment by vadasambar** [comment]
If you need help or clarification on the issue, please comment here or reach out to `@vadasambar` in Keptn slack.

**Comment by tarangverma** [comment]
can i take up this issue

**Comment by tarangverma** [comment]
additionally: can we add contributing guide to this repo is it a good option..

**Comment by vadasambar** [comment]
@tarangverma I am open to the idea. 

Do you think we can improve/add something to https://github.com/keptn-sandbox/datadog-service#development? Or have a different CONTRIBUTING.md altogether? If yes, what are the benefits to do so?
